import { Roboto, Rubik } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers/ThemeProvider";
import Header from "./_components/mainComponents/Header";
import ReactQueryProvider from "./providers/ReactQueryProvider";

const dmSans = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Somana | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ReactQueryProvider>
            <div className="fixed top-0 w-full z-10">
              <Header />
            </div>

            {children}
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
